### ISSUE TITLE
Account balance Zero

### ISSUE THREAD

**Issue by madhav-halbe** [sidebetz/feedback#10]
**Describe the bug**
I had a healthy account balance >10K. After logging in from a different account, logging out and then re-logging in from the first account (where balance was >10K), it shows my account balance to be Zero.

**Comment by duck-tape** [comment]
@madhav-halbe in order to make this actionable/debugable please provide specifics on username of 1'st account, 2nd account, etc. if this issue is repeatable, screenshots showing this would be useful

**Comment by madhav-halbe** [comment]
Can't replicate this, hence closing for now.
