### ISSUE TITLE
Betting: High Stakes Poker Video: Unable to bet for a few hands after hand #1

### ISSUE THREAD

**Issue by madhav-halbe** [sidebetz/feedback#2]
Environment: Beta

While testing the high stakes poker game, the odds from hand # 2 till hand # 5 or 6 (Not sure as hand # is not displayed) are not shown, which do not let a user bet on any player.

**Comment by duck-tape** [comment]
Potentially resolved by https://github.com/sidebetz/sidebetz/pull/254

**Comment by duck-tape** [comment]
@madhav-halbe This issue has been fixed please confirm and close
