### ISSUE TITLE
Betting: poker after dark

### ISSUE THREAD

**Issue by rajen71** [sidebetz/feedback#3]
1. there was no sound whilst the video was in play. 

2. the 5th hand which is the last hand , I made three bets on Johnny does it , he won the hand , but I did not get any winnings it showed loss in ledger and the balance did not reflect my winnings.

3. where are we going to put SideBetz logo and  name on the screen?

**Comment by duck-tape** [comment]
@rajen71 per our call, we  have ruled the following:

1. not replicable
2. know issue being tracked as https://github.com/sidebetz/sidebetz/issues/257

3. a recommendation on where the logo needs to be is solicited.

**Comment by duck-tape** [comment]
assigning this back to @rajen71 since 2 of the 3 issues mentioned have been resolved and recommendation on the 3rd is requried
