### ISSUE TITLE
Betting: Color of odds

### ISSUE THREAD

**Issue by madhav-halbe** [sidebetz/feedback#4]
We should have the odds on the fav player to be colored green and the underdog odds need to be red colored.

**Comment by duck-tape** [comment]
@madhav-halbe can you please add the additional appropriate information such as +ve value of odds or -ve value of odds to clarify what are odds for favorite player vs underdog please assign the ticket back to me once this is clarified.

**Comment by madhav-halbe** [comment]
Fav should always be green color and underdogs red.

**Comment by duck-tape** [comment]
@madhav-halbe This is what we show today:
<img width="1454" alt="image" src="https://github.com/user-attachments/assets/854a01a8-06b3-4460-8562-4cfe47f15b41">

And just to confirm:
- favorites are players whose odds are negative
- underdogs are players whose odds are positive

So in the example above we want Bruce's odds to be Green and Raver and Aaron's to be Red?

**Comment by madhav-halbe** [comment]
Correct

**Comment by duck-tape** [comment]
@madhav-halbe this issue has been resolved in beta please confirm and close the issue
