### ISSUE TITLE
Betting: Hand number sorting

### ISSUE THREAD

**Issue by madhav-halbe** [sidebetz/feedback#5]
![image](https://github.com/user-attachments/assets/6e7c111b-09a0-4861-b3ac-c181836ca60c)

Please take a look at hand sorting in the poker after dark video.

**Comment by duck-tape** [comment]
@madhav-halbe this has been fixed and verified as below:

https://github.com/user-attachments/assets/cc9b8a31-5ca8-4594-9bc8-405e713aff77

Please check this and close the ticket post confirmation
