### ISSUE TITLE
Betting: Tournament wallet balance not being transferred to Global wallet at the end of tournament

### ISSUE THREAD

**Issue by duck-tape** [sidebetz/feedback#6]
**Describe the bug**
When a tournament ends the balance in the tournament wallet is not being transferred back to the global wallet

**To Reproduce**
1. Go to "Home page" via https://beta.sidebetz.ai and sign in 
2. Make note of your global wallet amount
3. Click on "Poker After Dark Tournament"
4. Gameplay in the "Poker after dark" tab/window of browser for as long as you desire
5. Make note of your tournament wallet amount
6. In a new "Admin tool" tab/window go to https://beta.admintool.sidebetz.ai and sign in
7. Click on "Live" to turn the tournament off/end tournament for "Poker After Dark"
8. Go back to the "Poker After Dark" game play tab/window
9. Confirm that you see the end of tournament screen and make a note of the ending Tournament wallet balance
10. Switch back to "Admin tool" tab/window and enable "Poker after dark" tournament by clicking on the live button
11. In "Home page" refresh to see if the tournament wallet balance is added to the global wallet
12. Logout/login
13. Validate if the global wallet is reflecting the sum of original wallet from step2 + step9
14. Close the old "Poker after dark" tab/window
15. Click on "Poker After Dark Tournament"
16. Note the balance from step9 is still available in tournament wallet

**Expected behavior**
When the tournament ends the tournament balance should be added to the global wallet balance.

**Screenshots**
https://github.com/user-attachments/assets/7bb65fce-6849-45ca-b132-9abc720879bf

**Desktop (please complete the following information):**
 - OS: Mac OS X 14.5
 - Browser Arc - Chromium based
 - Version Version 1.54.0 (52220)

**Additional context**

**Comment by duck-tape** [comment]
Confirming this has been fixed per DB permission fix discussed and implemented at https://3.basecamp.com/5790766/buckets/37242084/chats/7334919787@7675653038

**Comment by milmanDev** [comment]
This will be resolved along with #437 as both are related to DB permissions issue. 

Moving to Done.
