### ISSUE TITLE
Betting: Hand #21 and 22: Beta version: 20 hands high stakes game

### ISSUE THREAD

**Issue by madhav-halbe** [sidebetz/feedback#7]
In hand # 21, tan is in the hand but no odds are shown for him. Also, odds for a player who has folded are shown. Same with hand # 22

**Comment by madhav-halbe** [comment]
<img width="1468" alt="Screenshot 2024-08-05 at 11 01 23 AM" src="https://github.com/user-attachments/assets/f6476e61-ff94-4496-b587-b5fedd555245">

**Comment by mrnthv** [comment]
[HandNum20_21_22.json](https://github.com/user-attachments/files/16511176/HandNum20_21_22.json)
@madhav-halbe @duck-tape can you take a look at the small json with just hands 20, 21 and 22
Please confirm if you are referring to the same hands. If yes, then also verify the odds if they are matching the game state.

From my viewing I can see a discrepancy in Tan's odds in Hand 21. He is in game but there are no odds shown briefly for him.

**Comment by mrnthv** [comment]
FYI, I have found a bug in handling CHECK events. Most probably Tan's inconsistent odds is related to that.

**Comment by duck-tape** [comment]
@madhav-halbe The fix for this has been pushed please validate and close
