### ISSUE TITLE
Betting: Odds display in actions should be rounded without decimals

### ISSUE THREAD

**Issue by madhav-halbe** [sidebetz/feedback#8]
Odds shown in action are shown with .00 decimals. Need absolute numbers without the .00.

**Comment by duck-tape** [comment]
@madhav-halbe please confirm that you would like the odds show in the actions in the red box to be rounded to the nearest whole number correct?
![image](https://github.com/user-attachments/assets/8e65b9c0-194d-4a7d-a7fb-f0bed96d393f)

**Comment by achampagnedev** [comment]
@duck-tape @madhav-halbe I also suppose the coins earned/lost can be shown without the decimal ? eg: 1000, 1872, 3647, 9000

**Comment by madhav-halbe** [comment]
@achampagnedev Yes

**Comment by duck-tape** [comment]
@achampagnedev since you are in there you may want to tackle #13 along with this as well

**Comment by achampagnedev** [comment]
@duck-tape was already on it ;) :)

**Comment by duck-tape** [comment]
Resolved in dev, will provide ETA for beta ASAP.
<img width="461" alt="image" src="https://github.com/user-attachments/assets/bfddfedd-ee7c-475a-96f7-75d24a10e0c6">
