### ISSUE TITLE
Registration when secondary email used is from sidebetz.ai domain

### ISSUE THREAD

**Issue by madhav-halbe** [sidebetz/feedback#9]
**Describe the bug**
When I try to register and use my secondary email as madhav@sidebetz.ai or username@sidebetz.ai, registrations is not successful.

**To Reproduce**
Try to use secondary email as your sidebetz.ai email

**Comment by duck-tape** [comment]
@JMkrish I am not sure if this has been fixed yet if it has please tag the PR as such or add a comment in here and I can move it to the approriate column on the project board.

**Comment by JMkrish** [comment]
> @JMkrish I am not sure if this has been fixed yet if it has please tag the PR as such or add a comment in here and I can move it to the approriate column on the project board.

@duck-tape I just submitted a PR to address this issue.

**Comment by duck-tape** [comment]
@JMkrish can you please advocate for this to be merged and pushed to main dev ASAP

**Comment by JMkrish** [comment]
Hi @JavierFerrerGomez  & @achampagnedev,

Could you please review this PR and provide your feedback on it as soon as possible?

**Comment by JMkrish** [comment]
@duck-tape
Now it is in main-dev. Can you test it once.

**Comment by duck-tape** [comment]
@JMkrish please work with @madhav-halbe to test this

**Comment by madhav-halbe** [comment]
Tested and works.
